name: Create PR on Push

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create PR
      run: |
        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
        pr_exists=$(gh pr list --search="is:open" --json number  --base main --head $branch_name --jq ".[].number")
        if [[ -n "$pr_exists" ]]; then
          echo "PR already exists (PR Number: $pr_number). Closing..."
        else
          gh pr create --base main --head "$branch_name" -t "Sync Main: Update with $branch_name" 
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
