name: Create PR on Push

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create PR
      run: |
        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
        pr_exists=$(gh pr list --base main --head "$branch_name" -q ".state==OPEN")
        echo $pr_exists
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
