name: Create PR on Push

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create PR
      run: |
        git show origin/main:package.json | jq -r .version
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
